export const STOP_INFO = {
  START: 'STOP_INFO_LOAD_START',
  SUCCESS: 'STOP_INFO_LOAD_SUCCESS',
  FAILURE: 'STOP_INFO_LOAD_SUCCESS'
}

export const ARRIVALS = {
  START: 'ARRIVALS_LOAD_START',
  SUCCESS: 'ARRIVALS_LOAD_SUCCESS',
  FAILURE: 'ARRIVALS_LOAD_SUCCESS'
}
