export const STOP_INFO = {
  START: 'STOP_INFO_LOAD_START',
  SUCCESS: 'STOP_INFO_LOAD_SUCCESS',
  FAILURE: 'STOP_INFO_LOAD_FAILURE'
}

export const ARRIVALS = {
  START: 'ARRIVALS_LOAD_START',
  SUCCESS: 'ARRIVALS_LOAD_SUCCESS',
  FAILURE: 'ARRIVALS_LOAD_FAILURE'
}

export const GEOLOCATION = {
  START: 'GEOLOCATION_UPDATE_START',
  SUCCESS: 'GEOLOCATION_UPDATE_SUCCESS',
  FAILURE: 'GEOLOCATION_UPDATE_FAILURE'
}

export const NEARBY_STOPS = {
  START: 'NEARBY_STOPS_LOAD_START',
  SUCCESS: 'NEARBY_STOPS_LOAD_SUCCESS',
  FAILURE: 'NEARBY_STOPS_LOAD_FAILURE'
}
