export const STOP_INFO = {
  START: 'STOP_INFO_LOAD_START',
  SUCCESS: 'STOP_INFO_LOAD_SUCCESS',
  FAILURE: 'STOP_INFO_LOAD_FAILURE'
}

export const ARRIVALS = {
  START: 'ARRIVALS_LOAD_START',
  SUCCESS: 'ARRIVALS_LOAD_SUCCESS',
  FAILURE: 'ARRIVALS_LOAD_FAILURE'
}

export const USER_LOCATION = {
  START: 'USER_LOCATION_UPDATE_START',
  SUCCESS: 'USER_LOCATION_UPDATE_SUCCESS',
  FAILURE: 'USER_LOCATION_UPDATE_FAILURE'
}

export const NEARBY_STOPS = {
  START: 'NEARBY_STOPS_LOAD_START',
  SUCCESS: 'NEARBY_STOPS_LOAD_SUCCESS',
  FAILURE: 'NEARBY_STOPS_LOAD_FAILURE'
}

export const FAVORITES = {
  START: 'FAVORITES_UPDATE_START',
  SUCCESS: 'FAVORITES_UPDATE_SUCCESS',
  FAILURE: 'FAVORITES_UPDATE_FAILURE'
}

export const MAP_CENTER = {
  START: 'MAP_CENTER_UPDATE_START',
  SUCCESS: 'MAP_CENTER_UPDATE_SUCCESS',
  FAILURE: 'MAP_CENTER_UPDATE_FAILURE'
}
