export const ARRIVALS_LOAD_START = 'ARRIVALS_LOAD_START';
export const ARRIVALS_LOAD_SUCCESS = 'ARRIVALS_LOAD_SUCCESS';
export const ARRIVALS_LOAD_FAILURE = 'ARRIVALS_LOAD_FAILURE';

export const STOP_INFO_LOAD_START = 'STOP_INFO_LOAD_START';
export const STOP_INFO_LOAD_SUCCESS = 'STOP_INFO_LOAD_SUCCESS';
export const STOP_INFO_LOAD_FAILURE = 'STOP_INFO_LOAD_FAILURE';

// import _keyBy from 'lodash/keyBy';

// module.exports = _keyBy([
//   'ARRIVALS_LOAD_START',
//   'ARRIVALS_LOAD_SUCCESS',
//   'ARRIVALS_LOAD_FAILURE',
//   'STOP_INFO_LOAD_START',
//   'STOP_INFO_LOAD_SUCCESS',
//   'STOP_INFO_LOAD_FAILURE'
// ]);
